name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        go: [1.15]
        test-tags: ['']
    name: ${{ matrix.os }} @ Go ${{ matrix.go }} ${{ matrix.test-tags }}
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      TESTTAGS: ${{ matrix.test-tags }}
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Set GOPATH and PATH
        run: |
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: make tools

      - name: Run Check
        run: |
          make vet
          make fmt-check
          make misspell-check

      - name: Run Tests
        run: make test

      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.15 && matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)
  gitter-failure:
    needs: test
    if: failure()
    env:
      MESSAGE: 'GitHub Actions [${{ github.repository }}] (${{ github.ref }}) [still failing](${{ github.event_path }}) (github.run_number)'
    runs-on: ubuntu-latest
    steps:
    - run: curl -d message="$MESSAGE" -d level=error https://webhooks.gitter.im/e/0d218e23e366f63de920
  gitter-success:
    needs: test
    if: success()
    env:
      MESSAGE: 'GitHub Actions [${{ github.repository }}] (${{ github.ref }}) [normal](${{ github.event_path }}) (github.run_number)'
    runs-on: ubuntu-latest
    steps:
      - run: curl -d message="$MESSAGE" -d https://webhooks.gitter.im/e/0d218e23e366f63de920
