name: Run Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    strategy:
      matrix:
        os: [windows-latest]
        go: [1.15]
        test-tags: ['']
    name: ${{ matrix.os }} @ Go ${{ matrix.go }} ${{ matrix.test-tags }}
    runs-on: ${{ matrix.os }}
    env:
      GO111MODULE: on
      TESTTAGS: ${{ matrix.test-tags }}
      GOPROXY: https://proxy.golang.org
    steps:
      - name: Set up Go ${{ matrix.go }}
        uses: actions/setup-go@v1
        with:
          go-version: ${{ matrix.go }}

      - name: Set GOPATH and PATH
        run: |
          xxx
          echo "GOPATH=$(dirname $GITHUB_WORKSPACE)" >> $GITHUB_ENV
          echo "$(dirname $GITHUB_WORKSPACE)/bin" >> $GITHUB_PATH
        shell: bash

      - name: Checkout Code
        uses: actions/checkout@v1
        with:
          ref: ${{ github.ref }}

      - name: Install Dependencies
        run: make tools

      - name: Run Check
        run: |
          make vet
          make fmt-check
          make misspell-check

      - name: Run Tests
        run: make test

      - name: Upload coverage to Codecov
        if: success() && matrix.go == 1.15 && matrix.os == 'ubuntu-latest'
        run: bash <(curl -s https://codecov.io/bash)
  gitter-failure:
    needs: test
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: |
          $(if [ "${{ github.event.pull_request }}" -ne "" ]; then export PR_OR_COMPARE="${{ github.event.pull_request.diff_url }}/files"; else export PR_OR_COMPARE="${{ github.event.compare }}"; fi)
          echo $PR_OR_COMPARE
          curl -d message="GitHub Actions [$GITHUB_REPOSITORY]($PR_OR_COMPARE) ($GITHUB_REF) [still failing]($GITHUB_API_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) ($GITHUB_RUN_NUMBER)" -d level=error https://webhooks.gitter.im/e/0d218e23e366f63de920

  gitter-success:
    needs: test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - run: |
          $(if [ "${{ github.event.pull_request }}" -ne "" ]; then export PR_OR_COMPARE="${{ github.event.pull_request.diff_url }}/files"; else export PR_OR_COMPARE="${{ github.event.compare }}"; fi)
          echo $PR_OR_COMPARE
          curl -d message="GitHub Actions [$GITHUB_REPOSITORY]($PR_OR_COMPARE) ($GITHUB_REF) [normal]($GITHUB_API_URL/$GITHUB_REPOSITORY/actions/runs/$GITHUB_RUN_ID) ($GITHUB_RUN_NUMBER)" https://webhooks.gitter.im/e/0d218e23e366f63de920
